import Head from "next/head";
import Layout from "../components/layout/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Bookings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex items-center justify-center">
          <h1>Bookings</h1>
        </div>
      </Layout>
    </div>
  );
}
