import Head from "next/head";
import BookingSteps from "../components/booking/BookingSteps";
import Layout from "../components/layout/Layout";

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex items-center justify-center">
        <BookingSteps />
        </div>
      </Layout>
    </div>
  );
}
