import Head from "next/head";
import Image from "next/image";
import Hero from "../components/landing/Hero";
import StoreGallery from "../components/landing/StoreGallery";
import StoreHero from "../components/landing/StoreHero";
import Layout from "../components/layout/Layout";
import { useStore } from "../context/store-context";

export default function Home() {
  const { store } = useStore();

  if (!store) {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          <Hero />
          <StoreGallery />
        </Layout>
      </div>
    );
  } else {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          <StoreHero />
        </Layout>
      </div>
    );
  }
}
